name: auto-format
on: pull_request
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: autoformat terraform
        run: make format
      - name: Check for modified files
        id: git-check
        run: echo "modified=$(if git diff-index --quiet HEAD --; then echo 'false'; else echo 'true'; fi)" >> $GITHUB_OUTPUT
      - name: Push Changes
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'chris@chrisvanlaw.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git commit -am "style: autoformat terraform"
          git push